use serde::Deserialize;
use serde::Serialize;

use super::*;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionEvent {
  /// Unique identifier of the trader's account. Used to match responses to trader's accounts.
  pub ctid_trader_account_id: i64,
  /// Type of the order operation. For example: ACCEPTED, FILLED, etc.
  pub execution_type: ExecutionType,
  /// Reference to the position linked with the execution
  pub position: Option<Position>,
  /// Reference to the initial order.
  pub order: Option<Order>,
  /// Reference to the deal (execution).
  pub deal: Option<Deal>,
  /// Reference to the Bonus Deposit or Withdrawal operation.
  pub bonus_deposit_withdraw: Option<BonusDepositWithdraw>,
  /// Reference to the Deposit or Withdrawal operation.
  pub deposit_withdraw: Option<DepositWithdraw>,
  /// The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
  pub error_code: Option<String>,
  /// If TRUE then the event generated by the server logic instead of the trader's request. (e.g. stop-out).
  pub is_server_event: Option<bool>,
}

impl TryFrom<kit_ctrader_proto::ProtoOaExecutionEvent> for ExecutionEvent {
  type Error = anyhow::Error;

  fn try_from(
    execution_event: kit_ctrader_proto::ProtoOaExecutionEvent
  ) -> Result<Self, Self::Error> {
    Ok(ExecutionEvent {
      ctid_trader_account_id: execution_event.ctid_trader_account_id,
      execution_type: ExecutionType::try_from(execution_event.execution_type)?,
      error_code: execution_event.error_code,
      is_server_event: execution_event.is_server_event,
      position: match execution_event.position {
        Some(position) => Some(Position::try_from(position)?),
        None => None,
      },
      order: match execution_event.order {
        Some(order) => Some(Order::try_from(order)?),
        None => None,
      },
      deal: match execution_event.deal {
        Some(deal) => Some(Deal::try_from(deal)?),
        None => None,
      },
      bonus_deposit_withdraw: match execution_event.bonus_deposit_withdraw {
        Some(bonus_deposit_withdraw) => {
          Some(BonusDepositWithdraw::try_from(bonus_deposit_withdraw)?)
        }
        None => None,
      },
      deposit_withdraw: match execution_event.deposit_withdraw {
        Some(deposit_withdraw) => Some(DepositWithdraw::try_from(deposit_withdraw)?),
        None => None,
      },
    })
  }
}
