[package]
name = "onlytrades_ctrader_proto"
version = "0.0.0-local"
authors = ["David Alsh"]
repository = "https://github.com/alshdavid/onlytrades.live"
description = "Trade Automation Refined"
edition = "2024"
license = "MIT"

[lib]
path = "./lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
prost = { workspace = true }
