[package]
name = "onlytrades_ctrader_proto"
version = "0.0.0-local"
authors = ["David Alsh"]
repository = "https://github.com/alshdavid/onlytrades.live"
description = "Trade Automation Refined"
edition = "2024"
license = "MIT"

[lib]
path = "./lib.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
dashmap = { workspace = true }
num_enum = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-native-tls = { workspace = true }
