[package]
name = "onlytrades_bot"
version = "0.0.0-local"
authors = ["David Alsh"]
repository = "https://github.com/alshdavid/onlytrades.live"
description = "Trade Automation Refined"
edition = "2024"
license = "MIT"

[lib]
name = "onlytrades_bot"
path = "./lib.rs"

[dependencies]
onlytrades_macros = { workspace = true }
kit_ctrader = { workspace = true }
tokio = { workspace = true, features = ["rt"] }