use num_enum::IntoPrimitive;
use num_enum::TryFromPrimitive;
use serde::Deserialize;
use serde::Serialize;

#[derive(
  Clone,
  Copy,
  Debug,
  PartialEq,
  Eq,
  Hash,
  PartialOrd,
  Ord,
  TryFromPrimitive,
  IntoPrimitive,
  Serialize,
  Deserialize,
)]
#[repr(i32)]
pub enum OaPayloadType {
  ProtoOaApplicationAuthReq = 2100,
  ProtoOaApplicationAuthRes = 2101,
  ProtoOaAccountAuthReq = 2102,
  ProtoOaAccountAuthRes = 2103,
  ProtoOaVersionReq = 2104,
  ProtoOaVersionRes = 2105,
  ProtoOaNewOrderReq = 2106,
  ProtoOaTrailingSlChangedEvent = 2107,
  ProtoOaCancelOrderReq = 2108,
  ProtoOaAmendOrderReq = 2109,
  ProtoOaAmendPositionSltpReq = 2110,
  ProtoOaClosePositionReq = 2111,
  ProtoOaAssetListReq = 2112,
  ProtoOaAssetListRes = 2113,
  ProtoOaSymbolsListReq = 2114,
  ProtoOaSymbolsListRes = 2115,
  ProtoOaSymbolByIdReq = 2116,
  ProtoOaSymbolByIdRes = 2117,
  ProtoOaSymbolsForConversionReq = 2118,
  ProtoOaSymbolsForConversionRes = 2119,
  ProtoOaSymbolChangedEvent = 2120,
  ProtoOaTraderReq = 2121,
  ProtoOaTraderRes = 2122,
  ProtoOaTraderUpdateEvent = 2123,
  ProtoOaReconcileReq = 2124,
  ProtoOaReconcileRes = 2125,
  ProtoOaExecutionEvent = 2126,
  ProtoOaSubscribeSpotsReq = 2127,
  ProtoOaSubscribeSpotsRes = 2128,
  ProtoOaUnsubscribeSpotsReq = 2129,
  ProtoOaUnsubscribeSpotsRes = 2130,
  ProtoOaSpotEvent = 2131,
  ProtoOaOrderErrorEvent = 2132,
  ProtoOaDealListReq = 2133,
  ProtoOaDealListRes = 2134,
  ProtoOaSubscribeLiveTrendbarReq = 2135,
  ProtoOaUnsubscribeLiveTrendbarReq = 2136,
  ProtoOaGetTrendbarsReq = 2137,
  ProtoOaGetTrendbarsRes = 2138,
  ProtoOaExpectedMarginReq = 2139,
  ProtoOaExpectedMarginRes = 2140,
  ProtoOaMarginChangedEvent = 2141,
  ProtoOaErrorRes = 2142,
  ProtoOaCashFlowHistoryListReq = 2143,
  ProtoOaCashFlowHistoryListRes = 2144,
  ProtoOaGetTickdataReq = 2145,
  ProtoOaGetTickdataRes = 2146,
  ProtoOaAccountsTokenInvalidatedEvent = 2147,
  ProtoOaClientDisconnectEvent = 2148,
  ProtoOaGetAccountsByAccessTokenReq = 2149,
  ProtoOaGetAccountsByAccessTokenRes = 2150,
  ProtoOaGetCtidProfileByTokenReq = 2151,
  ProtoOaGetCtidProfileByTokenRes = 2152,
  ProtoOaAssetClassListReq = 2153,
  ProtoOaAssetClassListRes = 2154,
  ProtoOaDepthEvent = 2155,
  ProtoOaSubscribeDepthQuotesReq = 2156,
  ProtoOaSubscribeDepthQuotesRes = 2157,
  ProtoOaUnsubscribeDepthQuotesReq = 2158,
  ProtoOaUnsubscribeDepthQuotesRes = 2159,
  ProtoOaSymbolCategoryReq = 2160,
  ProtoOaSymbolCategoryRes = 2161,
  ProtoOaAccountLogoutReq = 2162,
  ProtoOaAccountLogoutRes = 2163,
  ProtoOaAccountDisconnectEvent = 2164,
  ProtoOaSubscribeLiveTrendbarRes = 2165,
  ProtoOaUnsubscribeLiveTrendbarRes = 2166,
  ProtoOaMarginCallListReq = 2167,
  ProtoOaMarginCallListRes = 2168,
  ProtoOaMarginCallUpdateReq = 2169,
  ProtoOaMarginCallUpdateRes = 2170,
  ProtoOaMarginCallUpdateEvent = 2171,
  ProtoOaMarginCallTriggerEvent = 2172,
  ProtoOaRefreshTokenReq = 2173,
  ProtoOaRefreshTokenRes = 2174,
  ProtoOaOrderListReq = 2175,
  ProtoOaOrderListRes = 2176,
  ProtoOaGetDynamicLeverageReq = 2177,
  ProtoOaGetDynamicLeverageRes = 2178,
  ProtoOaDealListByPositionIdReq = 2179,
  ProtoOaDealListByPositionIdRes = 2180,
  ProtoOaOrderDetailsReq = 2181,
  ProtoOaOrderDetailsRes = 2182,
  ProtoOaOrderListByPositionIdReq = 2183,
  ProtoOaOrderListByPositionIdRes = 2184,
  ProtoOaDealOffsetListReq = 2185,
  ProtoOaDealOffsetListRes = 2186,
  ProtoOaGetPositionUnrealizedPnlReq = 2187,
  ProtoOaGetPositionUnrealizedPnlRes = 2188,
}
impl OaPayloadType {
  /// String value of the enum field names used in the ProtoBuf definition.
  pub fn as_str_name(&self) -> &'static str {
    match self {
      Self::ProtoOaApplicationAuthReq => "PROTO_OA_APPLICATION_AUTH_REQ",
      Self::ProtoOaApplicationAuthRes => "PROTO_OA_APPLICATION_AUTH_RES",
      Self::ProtoOaAccountAuthReq => "PROTO_OA_ACCOUNT_AUTH_REQ",
      Self::ProtoOaAccountAuthRes => "PROTO_OA_ACCOUNT_AUTH_RES",
      Self::ProtoOaVersionReq => "PROTO_OA_VERSION_REQ",
      Self::ProtoOaVersionRes => "PROTO_OA_VERSION_RES",
      Self::ProtoOaNewOrderReq => "PROTO_OA_NEW_ORDER_REQ",
      Self::ProtoOaTrailingSlChangedEvent => "PROTO_OA_TRAILING_SL_CHANGED_EVENT",
      Self::ProtoOaCancelOrderReq => "PROTO_OA_CANCEL_ORDER_REQ",
      Self::ProtoOaAmendOrderReq => "PROTO_OA_AMEND_ORDER_REQ",
      Self::ProtoOaAmendPositionSltpReq => "PROTO_OA_AMEND_POSITION_SLTP_REQ",
      Self::ProtoOaClosePositionReq => "PROTO_OA_CLOSE_POSITION_REQ",
      Self::ProtoOaAssetListReq => "PROTO_OA_ASSET_LIST_REQ",
      Self::ProtoOaAssetListRes => "PROTO_OA_ASSET_LIST_RES",
      Self::ProtoOaSymbolsListReq => "PROTO_OA_SYMBOLS_LIST_REQ",
      Self::ProtoOaSymbolsListRes => "PROTO_OA_SYMBOLS_LIST_RES",
      Self::ProtoOaSymbolByIdReq => "PROTO_OA_SYMBOL_BY_ID_REQ",
      Self::ProtoOaSymbolByIdRes => "PROTO_OA_SYMBOL_BY_ID_RES",
      Self::ProtoOaSymbolsForConversionReq => "PROTO_OA_SYMBOLS_FOR_CONVERSION_REQ",
      Self::ProtoOaSymbolsForConversionRes => "PROTO_OA_SYMBOLS_FOR_CONVERSION_RES",
      Self::ProtoOaSymbolChangedEvent => "PROTO_OA_SYMBOL_CHANGED_EVENT",
      Self::ProtoOaTraderReq => "PROTO_OA_TRADER_REQ",
      Self::ProtoOaTraderRes => "PROTO_OA_TRADER_RES",
      Self::ProtoOaTraderUpdateEvent => "PROTO_OA_TRADER_UPDATE_EVENT",
      Self::ProtoOaReconcileReq => "PROTO_OA_RECONCILE_REQ",
      Self::ProtoOaReconcileRes => "PROTO_OA_RECONCILE_RES",
      Self::ProtoOaExecutionEvent => "PROTO_OA_EXECUTION_EVENT",
      Self::ProtoOaSubscribeSpotsReq => "PROTO_OA_SUBSCRIBE_SPOTS_REQ",
      Self::ProtoOaSubscribeSpotsRes => "PROTO_OA_SUBSCRIBE_SPOTS_RES",
      Self::ProtoOaUnsubscribeSpotsReq => "PROTO_OA_UNSUBSCRIBE_SPOTS_REQ",
      Self::ProtoOaUnsubscribeSpotsRes => "PROTO_OA_UNSUBSCRIBE_SPOTS_RES",
      Self::ProtoOaSpotEvent => "PROTO_OA_SPOT_EVENT",
      Self::ProtoOaOrderErrorEvent => "PROTO_OA_ORDER_ERROR_EVENT",
      Self::ProtoOaDealListReq => "PROTO_OA_DEAL_LIST_REQ",
      Self::ProtoOaDealListRes => "PROTO_OA_DEAL_LIST_RES",
      Self::ProtoOaSubscribeLiveTrendbarReq => "PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ",
      Self::ProtoOaUnsubscribeLiveTrendbarReq => "PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_REQ",
      Self::ProtoOaGetTrendbarsReq => "PROTO_OA_GET_TRENDBARS_REQ",
      Self::ProtoOaGetTrendbarsRes => "PROTO_OA_GET_TRENDBARS_RES",
      Self::ProtoOaExpectedMarginReq => "PROTO_OA_EXPECTED_MARGIN_REQ",
      Self::ProtoOaExpectedMarginRes => "PROTO_OA_EXPECTED_MARGIN_RES",
      Self::ProtoOaMarginChangedEvent => "PROTO_OA_MARGIN_CHANGED_EVENT",
      Self::ProtoOaErrorRes => "PROTO_OA_ERROR_RES",
      Self::ProtoOaCashFlowHistoryListReq => "PROTO_OA_CASH_FLOW_HISTORY_LIST_REQ",
      Self::ProtoOaCashFlowHistoryListRes => "PROTO_OA_CASH_FLOW_HISTORY_LIST_RES",
      Self::ProtoOaGetTickdataReq => "PROTO_OA_GET_TICKDATA_REQ",
      Self::ProtoOaGetTickdataRes => "PROTO_OA_GET_TICKDATA_RES",
      Self::ProtoOaAccountsTokenInvalidatedEvent => "PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED_EVENT",
      Self::ProtoOaClientDisconnectEvent => "PROTO_OA_CLIENT_DISCONNECT_EVENT",
      Self::ProtoOaGetAccountsByAccessTokenReq => "PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ",
      Self::ProtoOaGetAccountsByAccessTokenRes => "PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES",
      Self::ProtoOaGetCtidProfileByTokenReq => "PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_REQ",
      Self::ProtoOaGetCtidProfileByTokenRes => "PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_RES",
      Self::ProtoOaAssetClassListReq => "PROTO_OA_ASSET_CLASS_LIST_REQ",
      Self::ProtoOaAssetClassListRes => "PROTO_OA_ASSET_CLASS_LIST_RES",
      Self::ProtoOaDepthEvent => "PROTO_OA_DEPTH_EVENT",
      Self::ProtoOaSubscribeDepthQuotesReq => "PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_REQ",
      Self::ProtoOaSubscribeDepthQuotesRes => "PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_RES",
      Self::ProtoOaUnsubscribeDepthQuotesReq => "PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_REQ",
      Self::ProtoOaUnsubscribeDepthQuotesRes => "PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_RES",
      Self::ProtoOaSymbolCategoryReq => "PROTO_OA_SYMBOL_CATEGORY_REQ",
      Self::ProtoOaSymbolCategoryRes => "PROTO_OA_SYMBOL_CATEGORY_RES",
      Self::ProtoOaAccountLogoutReq => "PROTO_OA_ACCOUNT_LOGOUT_REQ",
      Self::ProtoOaAccountLogoutRes => "PROTO_OA_ACCOUNT_LOGOUT_RES",
      Self::ProtoOaAccountDisconnectEvent => "PROTO_OA_ACCOUNT_DISCONNECT_EVENT",
      Self::ProtoOaSubscribeLiveTrendbarRes => "PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_RES",
      Self::ProtoOaUnsubscribeLiveTrendbarRes => "PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_RES",
      Self::ProtoOaMarginCallListReq => "PROTO_OA_MARGIN_CALL_LIST_REQ",
      Self::ProtoOaMarginCallListRes => "PROTO_OA_MARGIN_CALL_LIST_RES",
      Self::ProtoOaMarginCallUpdateReq => "PROTO_OA_MARGIN_CALL_UPDATE_REQ",
      Self::ProtoOaMarginCallUpdateRes => "PROTO_OA_MARGIN_CALL_UPDATE_RES",
      Self::ProtoOaMarginCallUpdateEvent => "PROTO_OA_MARGIN_CALL_UPDATE_EVENT",
      Self::ProtoOaMarginCallTriggerEvent => "PROTO_OA_MARGIN_CALL_TRIGGER_EVENT",
      Self::ProtoOaRefreshTokenReq => "PROTO_OA_REFRESH_TOKEN_REQ",
      Self::ProtoOaRefreshTokenRes => "PROTO_OA_REFRESH_TOKEN_RES",
      Self::ProtoOaOrderListReq => "PROTO_OA_ORDER_LIST_REQ",
      Self::ProtoOaOrderListRes => "PROTO_OA_ORDER_LIST_RES",
      Self::ProtoOaGetDynamicLeverageReq => "PROTO_OA_GET_DYNAMIC_LEVERAGE_REQ",
      Self::ProtoOaGetDynamicLeverageRes => "PROTO_OA_GET_DYNAMIC_LEVERAGE_RES",
      Self::ProtoOaDealListByPositionIdReq => "PROTO_OA_DEAL_LIST_BY_POSITION_ID_REQ",
      Self::ProtoOaDealListByPositionIdRes => "PROTO_OA_DEAL_LIST_BY_POSITION_ID_RES",
      Self::ProtoOaOrderDetailsReq => "PROTO_OA_ORDER_DETAILS_REQ",
      Self::ProtoOaOrderDetailsRes => "PROTO_OA_ORDER_DETAILS_RES",
      Self::ProtoOaOrderListByPositionIdReq => "PROTO_OA_ORDER_LIST_BY_POSITION_ID_REQ",
      Self::ProtoOaOrderListByPositionIdRes => "PROTO_OA_ORDER_LIST_BY_POSITION_ID_RES",
      Self::ProtoOaDealOffsetListReq => "PROTO_OA_DEAL_OFFSET_LIST_REQ",
      Self::ProtoOaDealOffsetListRes => "PROTO_OA_DEAL_OFFSET_LIST_RES",
      Self::ProtoOaGetPositionUnrealizedPnlReq => "PROTO_OA_GET_POSITION_UNREALIZED_PNL_REQ",
      Self::ProtoOaGetPositionUnrealizedPnlRes => "PROTO_OA_GET_POSITION_UNREALIZED_PNL_RES",
    }
  }
  /// Creates an enum from field names used in the ProtoBuf definition.
  pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
    match value {
      "PROTO_OA_APPLICATION_AUTH_REQ" => Some(Self::ProtoOaApplicationAuthReq),
      "PROTO_OA_APPLICATION_AUTH_RES" => Some(Self::ProtoOaApplicationAuthRes),
      "PROTO_OA_ACCOUNT_AUTH_REQ" => Some(Self::ProtoOaAccountAuthReq),
      "PROTO_OA_ACCOUNT_AUTH_RES" => Some(Self::ProtoOaAccountAuthRes),
      "PROTO_OA_VERSION_REQ" => Some(Self::ProtoOaVersionReq),
      "PROTO_OA_VERSION_RES" => Some(Self::ProtoOaVersionRes),
      "PROTO_OA_NEW_ORDER_REQ" => Some(Self::ProtoOaNewOrderReq),
      "PROTO_OA_TRAILING_SL_CHANGED_EVENT" => Some(Self::ProtoOaTrailingSlChangedEvent),
      "PROTO_OA_CANCEL_ORDER_REQ" => Some(Self::ProtoOaCancelOrderReq),
      "PROTO_OA_AMEND_ORDER_REQ" => Some(Self::ProtoOaAmendOrderReq),
      "PROTO_OA_AMEND_POSITION_SLTP_REQ" => Some(Self::ProtoOaAmendPositionSltpReq),
      "PROTO_OA_CLOSE_POSITION_REQ" => Some(Self::ProtoOaClosePositionReq),
      "PROTO_OA_ASSET_LIST_REQ" => Some(Self::ProtoOaAssetListReq),
      "PROTO_OA_ASSET_LIST_RES" => Some(Self::ProtoOaAssetListRes),
      "PROTO_OA_SYMBOLS_LIST_REQ" => Some(Self::ProtoOaSymbolsListReq),
      "PROTO_OA_SYMBOLS_LIST_RES" => Some(Self::ProtoOaSymbolsListRes),
      "PROTO_OA_SYMBOL_BY_ID_REQ" => Some(Self::ProtoOaSymbolByIdReq),
      "PROTO_OA_SYMBOL_BY_ID_RES" => Some(Self::ProtoOaSymbolByIdRes),
      "PROTO_OA_SYMBOLS_FOR_CONVERSION_REQ" => Some(Self::ProtoOaSymbolsForConversionReq),
      "PROTO_OA_SYMBOLS_FOR_CONVERSION_RES" => Some(Self::ProtoOaSymbolsForConversionRes),
      "PROTO_OA_SYMBOL_CHANGED_EVENT" => Some(Self::ProtoOaSymbolChangedEvent),
      "PROTO_OA_TRADER_REQ" => Some(Self::ProtoOaTraderReq),
      "PROTO_OA_TRADER_RES" => Some(Self::ProtoOaTraderRes),
      "PROTO_OA_TRADER_UPDATE_EVENT" => Some(Self::ProtoOaTraderUpdateEvent),
      "PROTO_OA_RECONCILE_REQ" => Some(Self::ProtoOaReconcileReq),
      "PROTO_OA_RECONCILE_RES" => Some(Self::ProtoOaReconcileRes),
      "PROTO_OA_EXECUTION_EVENT" => Some(Self::ProtoOaExecutionEvent),
      "PROTO_OA_SUBSCRIBE_SPOTS_REQ" => Some(Self::ProtoOaSubscribeSpotsReq),
      "PROTO_OA_SUBSCRIBE_SPOTS_RES" => Some(Self::ProtoOaSubscribeSpotsRes),
      "PROTO_OA_UNSUBSCRIBE_SPOTS_REQ" => Some(Self::ProtoOaUnsubscribeSpotsReq),
      "PROTO_OA_UNSUBSCRIBE_SPOTS_RES" => Some(Self::ProtoOaUnsubscribeSpotsRes),
      "PROTO_OA_SPOT_EVENT" => Some(Self::ProtoOaSpotEvent),
      "PROTO_OA_ORDER_ERROR_EVENT" => Some(Self::ProtoOaOrderErrorEvent),
      "PROTO_OA_DEAL_LIST_REQ" => Some(Self::ProtoOaDealListReq),
      "PROTO_OA_DEAL_LIST_RES" => Some(Self::ProtoOaDealListRes),
      "PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ" => Some(Self::ProtoOaSubscribeLiveTrendbarReq),
      "PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_REQ" => Some(Self::ProtoOaUnsubscribeLiveTrendbarReq),
      "PROTO_OA_GET_TRENDBARS_REQ" => Some(Self::ProtoOaGetTrendbarsReq),
      "PROTO_OA_GET_TRENDBARS_RES" => Some(Self::ProtoOaGetTrendbarsRes),
      "PROTO_OA_EXPECTED_MARGIN_REQ" => Some(Self::ProtoOaExpectedMarginReq),
      "PROTO_OA_EXPECTED_MARGIN_RES" => Some(Self::ProtoOaExpectedMarginRes),
      "PROTO_OA_MARGIN_CHANGED_EVENT" => Some(Self::ProtoOaMarginChangedEvent),
      "PROTO_OA_ERROR_RES" => Some(Self::ProtoOaErrorRes),
      "PROTO_OA_CASH_FLOW_HISTORY_LIST_REQ" => Some(Self::ProtoOaCashFlowHistoryListReq),
      "PROTO_OA_CASH_FLOW_HISTORY_LIST_RES" => Some(Self::ProtoOaCashFlowHistoryListRes),
      "PROTO_OA_GET_TICKDATA_REQ" => Some(Self::ProtoOaGetTickdataReq),
      "PROTO_OA_GET_TICKDATA_RES" => Some(Self::ProtoOaGetTickdataRes),
      "PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED_EVENT" => {
        Some(Self::ProtoOaAccountsTokenInvalidatedEvent)
      }
      "PROTO_OA_CLIENT_DISCONNECT_EVENT" => Some(Self::ProtoOaClientDisconnectEvent),
      "PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ" => Some(Self::ProtoOaGetAccountsByAccessTokenReq),
      "PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES" => Some(Self::ProtoOaGetAccountsByAccessTokenRes),
      "PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_REQ" => Some(Self::ProtoOaGetCtidProfileByTokenReq),
      "PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_RES" => Some(Self::ProtoOaGetCtidProfileByTokenRes),
      "PROTO_OA_ASSET_CLASS_LIST_REQ" => Some(Self::ProtoOaAssetClassListReq),
      "PROTO_OA_ASSET_CLASS_LIST_RES" => Some(Self::ProtoOaAssetClassListRes),
      "PROTO_OA_DEPTH_EVENT" => Some(Self::ProtoOaDepthEvent),
      "PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_REQ" => Some(Self::ProtoOaSubscribeDepthQuotesReq),
      "PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_RES" => Some(Self::ProtoOaSubscribeDepthQuotesRes),
      "PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_REQ" => Some(Self::ProtoOaUnsubscribeDepthQuotesReq),
      "PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_RES" => Some(Self::ProtoOaUnsubscribeDepthQuotesRes),
      "PROTO_OA_SYMBOL_CATEGORY_REQ" => Some(Self::ProtoOaSymbolCategoryReq),
      "PROTO_OA_SYMBOL_CATEGORY_RES" => Some(Self::ProtoOaSymbolCategoryRes),
      "PROTO_OA_ACCOUNT_LOGOUT_REQ" => Some(Self::ProtoOaAccountLogoutReq),
      "PROTO_OA_ACCOUNT_LOGOUT_RES" => Some(Self::ProtoOaAccountLogoutRes),
      "PROTO_OA_ACCOUNT_DISCONNECT_EVENT" => Some(Self::ProtoOaAccountDisconnectEvent),
      "PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_RES" => Some(Self::ProtoOaSubscribeLiveTrendbarRes),
      "PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_RES" => Some(Self::ProtoOaUnsubscribeLiveTrendbarRes),
      "PROTO_OA_MARGIN_CALL_LIST_REQ" => Some(Self::ProtoOaMarginCallListReq),
      "PROTO_OA_MARGIN_CALL_LIST_RES" => Some(Self::ProtoOaMarginCallListRes),
      "PROTO_OA_MARGIN_CALL_UPDATE_REQ" => Some(Self::ProtoOaMarginCallUpdateReq),
      "PROTO_OA_MARGIN_CALL_UPDATE_RES" => Some(Self::ProtoOaMarginCallUpdateRes),
      "PROTO_OA_MARGIN_CALL_UPDATE_EVENT" => Some(Self::ProtoOaMarginCallUpdateEvent),
      "PROTO_OA_MARGIN_CALL_TRIGGER_EVENT" => Some(Self::ProtoOaMarginCallTriggerEvent),
      "PROTO_OA_REFRESH_TOKEN_REQ" => Some(Self::ProtoOaRefreshTokenReq),
      "PROTO_OA_REFRESH_TOKEN_RES" => Some(Self::ProtoOaRefreshTokenRes),
      "PROTO_OA_ORDER_LIST_REQ" => Some(Self::ProtoOaOrderListReq),
      "PROTO_OA_ORDER_LIST_RES" => Some(Self::ProtoOaOrderListRes),
      "PROTO_OA_GET_DYNAMIC_LEVERAGE_REQ" => Some(Self::ProtoOaGetDynamicLeverageReq),
      "PROTO_OA_GET_DYNAMIC_LEVERAGE_RES" => Some(Self::ProtoOaGetDynamicLeverageRes),
      "PROTO_OA_DEAL_LIST_BY_POSITION_ID_REQ" => Some(Self::ProtoOaDealListByPositionIdReq),
      "PROTO_OA_DEAL_LIST_BY_POSITION_ID_RES" => Some(Self::ProtoOaDealListByPositionIdRes),
      "PROTO_OA_ORDER_DETAILS_REQ" => Some(Self::ProtoOaOrderDetailsReq),
      "PROTO_OA_ORDER_DETAILS_RES" => Some(Self::ProtoOaOrderDetailsRes),
      "PROTO_OA_ORDER_LIST_BY_POSITION_ID_REQ" => Some(Self::ProtoOaOrderListByPositionIdReq),
      "PROTO_OA_ORDER_LIST_BY_POSITION_ID_RES" => Some(Self::ProtoOaOrderListByPositionIdRes),
      "PROTO_OA_DEAL_OFFSET_LIST_REQ" => Some(Self::ProtoOaDealOffsetListReq),
      "PROTO_OA_DEAL_OFFSET_LIST_RES" => Some(Self::ProtoOaDealOffsetListRes),
      "PROTO_OA_GET_POSITION_UNREALIZED_PNL_REQ" => Some(Self::ProtoOaGetPositionUnrealizedPnlReq),
      "PROTO_OA_GET_POSITION_UNREALIZED_PNL_RES" => Some(Self::ProtoOaGetPositionUnrealizedPnlRes),
      _ => None,
    }
  }
}
