[package]
name = "onlytrades_ctrader"
version = "0.0.0-local"
authors = ["David Alsh"]
repository = "https://github.com/alshdavid/onlytrades.live"
description = "Trade Automation Refined"
edition = "2024"
license = "MIT"

[lib]
path = "./lib.rs"

[dependencies]
kit_ctrader_proto = { workspace = true }
kit_ctrader_rest = { workspace = true }
kit_ctrader_socket = { workspace = true }
